
% BPA-PP1 PROJECT - SUDOKU GENERATOR
% VUT BRNO
% ROMAIN FRESNEAU



%% GRAPHIC INTERFACE OBJECT -  MINIMUM 5

function main

global handles sudoku text delimiteur progressbar pourcentage

handles(1)=figure('units','pixels',...  % Fenêtre principale
    'position',[400 40 600 700],...         %size of the principal window
    'color',[0.5843 0.8157 0.9882],...      %color RGB Of the back color
    'numbertitle','off',...                             %Get rid of "Figure 1" in the title of the figure
    'name','SUDOKU-GEN',...             %Name of the window
    'menubar','none',...                        %remove the menubar from a figure
    'tag','interface');

handles(2)=uicontrol('style','pushbutton',...   % Bouton niveau facile
    'units','normalized',...                                    %Normalized units 
    'position',[0.32 0.05 0.37 0.05],...            %Position
    'string','Generate a sudoku grid',...    
    'callback',@grilleFacile,...                        %FunctionCall
    'tag','bouton-');

handles(3)=uicontrol('style','pushbutton',...   % Bouton menu principal
    'units','normalized',...
    'position',[0.05 0.05 0.2 0.05],...
    'string','Menu',...
    'callback',@menu,...     
    'tag','bouton-');

text(1)=uicontrol('style','text',...    % Texte d'accueil
        'units','normalized',...
        'position',[0 0.8 1 0.1],...
        'BackgroundColor',[0.5843 0.8157 0.9882],...
        'string','My sudoku project',...
        'FontSize',18); 
    
text(2)=uicontrol('style','text',...    % Texte
        'units','normalized',...
        'position',[0.1 0.7 0.8 0.1],...
        'BackgroundColor',[0.5843 0.8157 0.9882],...
        'string','This program can create a simple sudoku grid and can resolve it, I realized this project as part of the evaluation of BPA-PP1 in VUT Brno.',...
        'FontSize',12); 
    

text(3)=uicontrol('style','text',...    % Texte
        'units','normalized',...
        'position',[0 0.5 1 0.1],...
        'BackgroundColor',[0.5843 0.8157 0.9882],...
        'string','ROMAIN FRESNEAU POLYTECH ANGERS',...
        'FontSize',10); 
    
    text(4)=uicontrol('style','text',...    % Texte
        'units','normalized',...
        'position',[0 0.5 1 0.1],...
        'BackgroundColor',[0.5843 0.8157 0.9882],...
        'string','Press Bouton to call the generation function',...
        'FontSize',10); 
 % -------------------------------------------------------------------------
 % PROGRESS BAR WHEN WE GENERATE THE GRID
progressbar = uicontrol('style','text',...    % Texte
        'units','normalized',...
        'position',[0.1 0.45 0.00001 0.003],...
        'BackgroundColor',[0.1 0.1 0.1],...
        'string','',...
        'visible', 'off',...
        'FontSize',10);
    pourcentage = uicontrol('style','text',...    % Texte
        'units','normalized',...
        'position',[0.45 0.38 0.1 0.05],...
        'BackgroundColor',[0.925 0.913 0.687],...
        'string','0%',...
        'visible','off',...
        'FontSize',8);
% -------------------------------------------------------------------------
for i = 1:1:9   % Sudoku boxes generation from 1 to 9
    for j = 1:1:9
       sudoku(i,j)=uicontrol('style','edit',...
        'units','normalized',...
        'position',[-0.05+j*0.1 0.97-i*0.09 0.1 0.09],...       %Formula of positionning with test i and j
        'string','',...
        'visible','off',...                                                             %Not visible at the launch of the program
        'FontSize',30); 
    end
end
% -------------------------------------------------------------------------
% DRAW OF THE LINE OF THE GRID
delimiteur(1) = uicontrol('style','text',...
        'units','normalized',...
        'position',[0.05 0.7 0.91 0.005],...
        'string','',...
        'BackgroundColor',[0.1 0.1 0.1],...
        'visible','off',...
        'FontSize',30); 
    
delimiteur(2) = uicontrol('style','text',...
        'units','normalized',...
        'position',[0.05 0.43 0.91 0.005],...
        'string','',...
        'BackgroundColor',[0.1 0.1 0.1],...
        'visible','off',...
        'FontSize',30); 
    
delimiteur(3) = uicontrol('style','text',...
        'units','normalized',...
        'position',[0.345 0.16 0.005 0.82],...
        'string','',...
        'BackgroundColor',[0.1 0.1 0.1],...
        'visible','off',...
        'FontSize',30); 
    
delimiteur(4) = uicontrol('style','text',...
        'units','normalized',...
        'position',[0.645 0.16 0.005 0.82],...
        'string','',...
        'BackgroundColor',[0.1 0.1 0.1],...
        'visible','off',...
        'FontSize',30); 
    
delimiteur(5) = uicontrol('style','text',...
        'units','normalized',...
        'position',[0.04 0.97 0.92 0.01],...
        'string','',...
        'BackgroundColor',[0.1 0.1 0.1],...
        'visible','off',...
        'FontSize',30); 
    
delimiteur(6) = uicontrol('style','text',...
        'units','normalized',...
        'position',[0.04 0.15 0.01 0.82],...
        'string','',...
        'BackgroundColor',[0.1 0.1 0.1],...
        'visible','off',...
        'FontSize',30); 
    
delimiteur(7) = uicontrol('style','text',...
        'units','normalized',...
        'position',[0.95 0.15 0.01 0.82],...
        'string','',...
        'BackgroundColor',[0.1 0.1 0.1],...
        'visible','off',...
        'FontSize',30); 
    
delimiteur(8) = uicontrol('style','text',...
        'units','normalized',...
        'position',[0.04 0.15 0.92 0.01],...
        'string','',...
        'BackgroundColor',[0.1 0.1 0.1],...
        'visible','off',...
        'FontSize',30); 
 % -------------------------------------------------------------------------

%% FONCTIONS PRINCIPALES

function grilleFacile(obj, event)   % Génération d'une grille INITIALISATION

global handles sudoku text GrillePleine delimiteur progressbar pourcentage     %if several functions all declare a particular variable name as global , then they all share a single copy of that variable

 
set(handles(2),'enable','off');             %initially off
set(handles(3),'enable','off');

for i = 1:1:3   %from 1 to 3
    set(text(i),'visible','off');   % Removal of welcome texts
    drawnow                         %drawnow updates figures and processes any pending callbacks. Use this command if you modify graphics objects and want to see the updates on the screen immediately.
end

for i = 1:1:8
    set(delimiteur(i),'visible','off');         %Grid initially not drawed
end

for i = 1:1:9   % Grid Reset
    for j = 1:1:9
        set(sudoku(i,j),'string','');   
        set(sudoku(i,j),'BackgroundColor',[1 1 1]);
        set(sudoku(i,j),'enable','on');
        set(sudoku(i,j),'visible','off');
    end
end

drawnow
 % -------------------------------------------------------------------------   LOADING INFORMATION
set(text(4),'string','Génération of the grid.');
set(text(4),'visible','on');
set(progressbar,'position',[0.1 0.45 0.00001 0.003]);
set(pourcentage,'string','0%');

drawnow
 % -------------------------------------------------------------------------
 
 
 
 
 
 
  % -------------------------------------------------------------------------
  %PRINTING OF THE GRID
  
GrillePleine = getGrillePleine(progressbar, pourcentage);   % Synthesis of a full grid


for i = 1:1:8
    set(delimiteur(i),'visible','on');                  %Printing of the grid
end

GrilleFacile = genGrilleFacile(GrillePleine);   % Creation of the grid

for i = 1:1:9   % Update of the graphic grid
    for j = 1:1:9
        if(GrilleFacile(i,j) ~= 0)  % If box is not empty
            set(sudoku(i,j),'string',GrilleFacile(i,j));
            set(sudoku(i,j),'BackgroundColor',[0.9 0.9 0.9]);
            set(sudoku(i,j),'enable','inactive');
        end
        set(sudoku(i,j),'visible','on');
    end
end

set(text(4),'visible','off');
set(progressbar,'visible','off');
set(pourcentage,'visible','off');
set(handles(2),'string','Print Solution');
set(handles(2),'callback',@voirSolution);
set(handles(2),'enable','on');
set(handles(3),'enable','on');




function voirSolution(obj, event)

global sudoku GrillePleine

for i = 1:1:9
    for j = 1:1:9
        set(sudoku(i,j),'string',GrillePleine(i,j));
    end
end

function menu(obj, event)

global handles sudoku text delimiteur

for i = 1:1:4
    set(text(i),'visible','on');
end

for i = 1:1:8
    set(delimiteur(i),'visible','off');
end

for i = 1:1:9   % Réinitialisation de la grille
    for j = 1:1:9
        set(sudoku(i,j),'string','');   
        set(sudoku(i,j),'BackgroundColor',[1 1 1]);
        set(sudoku(i,j),'enable','on');
        set(sudoku(i,j),'visible','off');
    end
end

set(handles(2),'string','Générate Grid');
set(handles(2),'callback',@grilleFacile);
set(handles(3),'string','Menu');
set(handles(3),'callback',@menu);
set(text(4),'string','ROMAIN FRESNEAU');

